export const Users = [
    {
      "id":1,
      "Name": "Sergej Milinković-Savić",
      "Nationality": "Serbia",
      "Current_club": "Lazio",
      "League_Position": "Central Midfield",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 85,
      "Predicted_Sponsorship_value": "13695",
      "Current_Market_value": "63,000,000",
      "Sponsor": "Nike",
      "Individual_Awards": 5,
      "Total_Followers": "556148",
      "League":"Serie A",
      "Ad_value_equivalent":"178432"
    },
    {
      "id":2,
      "Name": "Declan Rice",
      "Nationality": "England",
      "Current_club": "West Ham United",
      "League_Position": "Defensive Midfield",
      "Myers_Briggs": "Inspirer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "White",
      "Overall_rating": 82,
      "Predicted_Sponsorship_value": "830694",
      "Current_Market_value": "63,000,001",
      "Sponsor": "adidas",
      "Individual_Awards": 4,
      "Total_Followers": "1581000",
      "League":"Premier League",
      "Ad_value_equivalent":"5642000"
    },
    {
      "id":3,
      "Name": "Mikel Oyarzabal",
      "Nationality": "Spain",
      "Current_club": "Real Sociedad",
      "League_Position": "Left Winger",
      "Myers_Briggs": "Artist, Performer",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 85,
      "Predicted_Sponsorship_value": "55692",
      "Current_Market_value": "63,000,002",
      "Sponsor": "Nike",
      "Individual_Awards": 1,
      "League":"LaLiga",
      "Total_Followers": "182300",
      "Ad_value_equivalent":"982800"
    },
    {
      "id":4,
      "Name": "Florian Wirtz",
      "Nationality": "Germany",
      "Current_club": "Bayer 04 Leverkusen",
      "League_Position": "Attacking Midfield",
      "Myers_Briggs": "Mechanic",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 79,
      "Predicted_Sponsorship_value": "48598",
      "Current_Market_value": "58,500,000",
      "Sponsor": "adidas",
      "Individual_Awards": 0,
      "League":"Budesliga",
      "Total_Followers": "215021",
      "Ad_value_equivalent":"1537900"
    },
    {
      "id":5,
      "Name": "Victor Osimhen",
      "Nationality": "Nigeria",
      "Current_club": "SSC Napoli",
      "League_Position": "Centre-Forward",
      "Myers_Briggs": "Mechanic",
      "Personality_Type": "Introvert",
      "Ethnicity": "Black",
      "Overall_rating": 81,
      "Predicted_Sponsorship_value": "188589",
      "Current_Market_value": "54,000,000",
      "Sponsor": "Nike",
      "Individual_Awards": 6,
      "League":"Serie A",
      "Total_Followers": "908700",
      "Ad_value_equivalent":"2566200"
    },
    {
      "id":6,
      "Name": "Wilfred Ndidi",
      "Nationality": "Nigeria",
      "Current_club": "Leicester City",
      "League_Position": "Defensive Midfield",
      "Myers_Briggs": "Inspirer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 85,
      "Predicted_Sponsorship_value": "30754",
      "Current_Market_value": "54,000,000",
      "Sponsor": "Nike",
      "Individual_Awards": 0,
      "League":"Premier League",
      "Total_Followers": "900600",
      "Ad_value_equivalent":"904540"
    },
    {
      "id":7,
      "Name": "Youri Tielemans",
      "Nationality": "Belgium",
      "Current_club": "Leicester City",
      "League_Position": "Central Midfield",
      "Myers_Briggs": "Protector",
      "Personality_Type": "Introvert",
      "Ethnicity": "Black",
      "Overall_rating": 85,
      "Predicted_Sponsorship_value": "108620",
      "Current_Market_value": "49,500,000",
      "Sponsor": "Nike",
      "Individual_Awards": 7,
      "League":"Premier League",
      "Total_Followers": "395535",
      "Ad_value_equivalent":"1519700"
    },
    {
      "id":8,
      "Name": "Piotr Zielinski",
      "Nationality": "Poland",
      "Current_club": "SSC Napoli",
      "League_Position": "Attacking Midfield",
      "Myers_Briggs": "Performer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "White",
      "Overall_rating": 81,
      "Predicted_Sponsorship_value": "5602",
      "Current_Market_value": "45,000,000",
      "Sponsor": "Nike",
      "Individual_Awards": 0,
      "League":"Serie A",
      "Total_Followers": "618013",
      "Ad_value_equivalent":"159604.9"
    },
    {
      "id":9,
      "Name": "James Maddison",
      "Nationality": "England",
      "Current_club": "Leicester City",
      "League_Position": "Attacking Midfield",
      "Myers_Briggs": "Visionary",
      "Personality_Type": "Extrovert",
      "Ethnicity": "White",
      "Overall_rating": 82,
      "Predicted_Sponsorship_value": "231374",
      "Current_Market_value": "45,000,000",
      "Sponsor": "Puma",
      "Individual_Awards": 5,
      "League":"Premier League",
      "Total_Followers": "1632400",
      "Ad_value_equivalent":"1692600"
    },
    {
      "id":10,
      "Name": "Lorenzo Insigne",
      "Nationality": "Italy",
      "Current_club": "SSC Napoli",
      "League_Position": "Left Winger",
      "Myers_Briggs": "Artist, Performer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "White",
      "Overall_rating": 86,
      "Predicted_Sponsorship_value": "344523",
      "Current_Market_value": "43,200,000",
      "Sponsor": "adidas",
      "Individual_Awards": 3,
      "League":"Serie A",
      "Total_Followers": "2398100",
      "Ad_value_equivalent":"1874600"
    },
    {
      "id":11,
      "Name": "Kalidou Koulibaly",
      "Nationality": "Senegal",
      "Current_club": "SSC Napoli",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Mechanic",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 86,
      "Predicted_Sponsorship_value": "148013",
      "Current_Market_value": "43,200,000",
      "Sponsor": "Puma",
      "Individual_Awards": 9,
      "League":"Serie A",
      "Total_Followers": "2146800",
      "Ad_value_equivalent":"874273.4"
    },
    {
      "id":12,
      "Name": "Caglar Söyüncü",
      "Nationality": "Turkey",
      "Current_club": "Leicester City",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "White",
      "Overall_rating": 80,
      "Predicted_Sponsorship_value": "1987",
      "Current_Market_value": "40,500,000",
      "Sponsor": "Nike",
      "Individual_Awards": 1,
      "League":"Premier League",
      "Total_Followers": "871300",
      "Ad_value_equivalent":"31040.1"
    },
    {
      "id":13,
      "Name": "Hirving Lozano",
      "Nationality": "Mexico",
      "Current_club": "SSC Napoli",
      "League_Position": "Right Winger",
      "Myers_Briggs": "Mechanic",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 81,
      "Predicted_Sponsorship_value": "172415",
      "Current_Market_value": "40,500,000",
      "Sponsor": "Nike",
      "Individual_Awards": 16,
      "League":"Serie A",
      "Total_Followers": "2184500",
      "Ad_value_equivalent":"1046500"
    },
    {
      "id":14,
      "Name": "Fabián Ruiz",
      "Nationality": "Spain",
      "Current_club": "SSC Napoli",
      "League_Position": "Central Midfield",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 82,
      "Predicted_Sponsorship_value": "31906",
      "Current_Market_value": "40,500,000",
      "Sponsor": "adidas",
      "Individual_Awards": 2,
      "League":"Serie A",
      "Total_Followers": "611000",
      "Ad_value_equivalent":"441177.1"
    },
    {
      "id":15,
      "Name": "Moussa Diaby",
      "Nationality": "France",
      "Current_club": "Bayer 04 Leverkusen",
      "League_Position": "Left Winger",
      "Myers_Briggs": "Artist, Performer",
      "Personality_Type": "Introvert",
      "Ethnicity": "Black",
      "Overall_rating": 81,
      "Predicted_Sponsorship_value": "70209",
      "Current_Market_value": "37,800,000",
      "Sponsor": "adidas",
      "Individual_Awards": 2,
      "League":"Budesliga",
      "Total_Followers": "328147",
      "Ad_value_equivalent":"1064700"
    },
    {
      "id":16,
      "Name": "Tomas Soucek",
      "Nationality": "Czech Republic",
      "Current_club": "West Ham United",
      "League_Position": "Defensive Midfield",
      "Myers_Briggs": "Mechanic",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 82,
      "Predicted_Sponsorship_value": "78380",
      "Current_Market_value": "37,800,000",
      "Sponsor": "adidas",
      "Individual_Awards": 4,
      "League":"Premier League",
      "Total_Followers": "282700",
      "Ad_value_equivalent":"1064700"
    },
    {
      "id":17,
      "Name": "Luis Alberto",
      "Nationality": "Spain",
      "Current_club": "SS Lazio",
      "League_Position": "Central Midfield",
      "Myers_Briggs": "Idealist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 68,
      "Predicted_Sponsorship_value": "53212",
      "Current_Market_value": "36,000,000",
      "Sponsor": "adidas",
      "Individual_Awards": 2,
      "League":"Serie A",
      "Total_Followers": "588900",
      "Ad_value_equivalent":"887268.2"
    },
    {
      "id":18,
      "Name": "Mikel Merino",
      "Nationality": "Spain",
      "Current_club": "Real Sociedad",
      "League_Position": "Central Midfield",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 83,
      "Predicted_Sponsorship_value": "28934",
      "Current_Market_value": "36,000,000",
      "Sponsor": "adidas",
      "Individual_Awards": 1,
      "League":"LaLiga",
      "Total_Followers": "194200",
      "Ad_value_equivalent":"522895.1"
    },
    {
      "id":19,
      "Name": "Edmond Tapsoba",
      "Nationality": "Burkina Faso",
      "Current_club": "Bayer 04 Leverkusen",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 81,
      "Predicted_Sponsorship_value": "10145",
      "Current_Market_value": "36,000,000",
      "Sponsor": "Puma",
      "Individual_Awards": 0,
      "League":"Budesliga",
      "Total_Followers": "60543",
      "Ad_value_equivalent":"313121.9"
    },
    {
      "id":20,
      "Name": "Alexander Isak",
      "Nationality": "Sweden",
      "Current_club": "Real Sociedad",
      "League_Position": "Centre-Forward",
      "Myers_Briggs": "Mechanic",
      "Personality_Type": "Introvert",
      "Ethnicity": "Black",
      "Overall_rating": 82,
      "Predicted_Sponsorship_value": "41778",
      "Current_Market_value": "36,000,000",
      "Sponsor": "adidas",
      "Individual_Awards": 2,
      "League":"LaLiga",
      "Total_Followers": "483751",
      "Ad_value_equivalent":"750986.6"
    },
    {
      "id":21,
      "Name": "Wesley Fofana",
      "Nationality": "France",
      "Current_club": "Leicester City",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 78,
      "Predicted_Sponsorship_value": "12038",
      "Current_Market_value": "36,000,000",
      "Sponsor": "adidas",
      "Individual_Awards": 0,
      "League":"Premier League",
      "Total_Followers": "339000",
      "Ad_value_equivalent":"385840"
    },
    {
      "id":22,
      "Name": "Ciro Immobile",
      "Nationality": "Italy",
      "Current_club": "SS Lazio",
      "League_Position": "Centre-Forward",
      "Myers_Briggs": "Scientist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 87,
      "Predicted_Sponsorship_value": "160466",
      "Current_Market_value": "34,200,000",
      "Sponsor": "adidas",
      "Individual_Awards": 13,
      "League":"Serie A",
      "Total_Followers": "2146000",
      "Ad_value_equivalent":"928200"
    },
    {
      "id":23,
      "Name": "Aurélien Tchouaméni",
      "Nationality": "France",
      "Current_club": "AS Monaco",
      "League_Position": "Defensive Midfield",
      "Myers_Briggs": "Inspirer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 80,
      "Predicted_Sponsorship_value": "14470",
      "Current_Market_value": "31,500,000",
      "Sponsor": "Nike",
      "Individual_Awards": 2,
      "League":"Ligue 1",
      "Total_Followers": "219000",
      "Ad_value_equivalent":"266611.8"
    },
    {
      "id":24,
      "Name": "Houssem Aouar",
      "Nationality": "France",
      "Current_club": "Olympique Lyon",
      "League_Position": "Central Midfield",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 81,
      "Predicted_Sponsorship_value": "11137",
      "Current_Market_value": "31,500,000",
      "Sponsor": "adidas",
      "Individual_Awards": 1,
      "League":"Ligue 1",
      "Total_Followers": "758400",
      "Ad_value_equivalent":"158640.3"
    },
    {
      "id":25,
      "Name": "Wissam Ben Yedder",
      "Nationality": "France",
      "Current_club": "AS Monaco",
      "League_Position": "Centre-Forward",
      "Myers_Briggs": "Mechanic",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 83,
      "Predicted_Sponsorship_value": "23599",
      "Current_Market_value": "31,500,000",
      "Sponsor": "Puma",
      "Individual_Awards": 2,
      "League":"Ligue 1",
      "Total_Followers": "763900",
      "Ad_value_equivalent":"419100.5"
    },
    {
      "id":26,
      "Name": "Harvey Barnes",
      "Nationality": "England",
      "Current_club": "Leicester City",
      "League_Position": "Left Midfield",
      "Myers_Briggs": "Artist, Idealist, Mechanic",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 80,
      "Predicted_Sponsorship_value": "77671",
      "Current_Market_value": "31,500,000",
      "Sponsor": "adidas",
      "Individual_Awards": 5,
      "League":"Premier League",
      "Total_Followers": "192100",
      "Ad_value_equivalent":"1164800"
    },
    {
      "id":27,
      "Name": "Lucas Paquetá",
      "Nationality": "Brazil",
      "Current_club": "Olympique Lyon",
      "League_Position": "Attacking Midfield",
      "Myers_Briggs": "Performer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "White",
      "Overall_rating": 82,
      "Predicted_Sponsorship_value": "131615",
      "Current_Market_value": "31,500,000",
      "Sponsor": "Nike",
      "Individual_Awards": 4,
      "League":"Ligue 1",
      "Total_Followers": "5646200",
      "Ad_value_equivalent":"316643.6"
    },
    {
      "id":28,
      "Name": "Kurt Zouma",
      "Nationality": "France",
      "Current_club": "West Ham United",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 81,
      "Predicted_Sponsorship_value": "150086",
      "Current_Market_value": "2,880,000",
      "Sponsor": "Nike",
      "Individual_Awards": 1,
      "League":"Premier League",
      "Total_Followers": "2537400",
      "Ad_value_equivalent":"842587.2"
    },
    {
      "id":29,
      "Name": "Nikola Vlasic",
      "Nationality": "Croatia",
      "Current_club": "West Ham United",
      "League_Position": "Attacking Midfield",
      "Myers_Briggs": "Performer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "White",
      "Overall_rating": 80,
      "Predicted_Sponsorship_value": "16789",
      "Current_Market_value": "27,000,000",
      "Sponsor": "Nike",
      "Individual_Awards": 2,
      "League":"Premier League",
      "Total_Followers": "138747",
      "Ad_value_equivalent":"237955.9"
    },
    {
      "id":30,
      "Name": "Matteo Politano",
      "Nationality": "Italy",
      "Current_club": "SSC Napoli",
      "League_Position": "Right Winger",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 81,
      "Predicted_Sponsorship_value": "9566",
      "Current_Market_value": "27,000,001",
      "Sponsor": "Nike",
      "Individual_Awards": 0,
      "League":"Serie A",
      "Total_Followers": "548600",
      "Ad_value_equivalent":"272545"
    },
    {
      "id":31,
      "Name": "Bruno Guimarães",
      "Nationality": "Brazil",
      "Current_club": "Olympique Lyon",
      "League_Position": "Central Midfield",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 80,
      "Predicted_Sponsorship_value": "5899",
      "Current_Market_value": "27,000,002",
      "Sponsor": "adidas",
      "Individual_Awards": 1,
      "League":"Ligue 1",
      "Total_Followers": "799300",
      "Ad_value_equivalent":"85075.9"
    },
    {
      "id":32,
      "Name": "Jarrod Bowen",
      "Nationality": "England",
      "Current_club": "West Ham United",
      "League_Position": "Right Winger",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 78,
      "Predicted_Sponsorship_value": "108162",
      "Current_Market_value": "27,000,003",
      "Sponsor": "adidas",
      "Individual_Awards": 3,
      "League":"Premier League",
      "Total_Followers": "157000",
      "Ad_value_equivalent":"1556100"
    },
    {
      "id":33,
      "Name": "Kevin Volland",
      "Nationality": "Germany",
      "Current_club": "AS Monaco",
      "League_Position": "Centre-Forward",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "White",
      "Overall_rating": 82,
      "Predicted_Sponsorship_value": "16085",
      "Current_Market_value": "27,000,004",
      "Sponsor": "Nike",
      "Individual_Awards": 2,
      "League":"Ligue 1",
      "Total_Followers": "370000",
      "Ad_value_equivalent":"289134.3"
    },
    {
      "id":34,
      "Name": "Ricardo Pereira",
      "Nationality": "Portugal",
      "Current_club": "Leicester City",
      "League_Position": "Right-Back",
      "Myers_Briggs": "Artist/Idealist",
      "Personality_Type": "Introvert",
      "Ethnicity": "Black",
      "Overall_rating": 84,
      "Predicted_Sponsorship_value": "15139",
      "Current_Market_value": "27,000,005",
      "Sponsor": "Nike",
      "Individual_Awards": 1,
      "League":"Premier League",
      "Total_Followers": "310900",
      "Ad_value_equivalent":"225279.6.632"
    },
    {
      "id":35,
      "Name": "Patrik Schick",
      "Nationality": "Czech Republic",
      "Current_club": "Bayer 04 Leverkusen",
      "League_Position": "Centre-Forward",
      "Myers_Briggs": "Mechanic",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 79,
      "Predicted_Sponsorship_value": "68006",
      "Current_Market_value": "25,200,000",
      "Sponsor": "Nike",
      "Individual_Awards": 3,
      "League":"Budesliga",
      "Total_Followers": "398329",
      "Ad_value_equivalent":"1046500"
    },
    {
      "id":36,
      "Name": "Boubacar Kamara",
      "Nationality": "France",
      "Current_club": "Olympique Marseille",
      "League_Position": "Defensive Midfield",
      "Myers_Briggs": "Inspirer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 81,
      "Predicted_Sponsorship_value": "16773",
      "Current_Market_value": "25,200,000",
      "Sponsor": "Nike",
      "Individual_Awards": 0,
      "League":"Ligue 1",
      "Total_Followers": "580000",
      "Ad_value_equivalent":"517699"
    },
    {
      "id":37,
      "Name": "Evan N'Dicka",
      "Nationality": "France",
      "Current_club": "Eintracht Frankfurt",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 77,
      "Predicted_Sponsorship_value": "2982",
      "Current_Market_value": "25,200,000",
      "Sponsor": "Puma",
      "Individual_Awards": 0,
      "League":"Budesliga",
      "Total_Followers": "29900",
      "Ad_value_equivalent":"96805.8"
    },
    {
      "id":38,
      "Name": "Timothy Castagne",
      "Nationality": "Belgium",
      "Current_club": "Leicester City",
      "League_Position": "Right-Back",
      "Myers_Briggs": "Artist/Idealist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 79,
      "Predicted_Sponsorship_value": "8553",
      "Current_Market_value": "25,200,000",
      "Sponsor": "Nike",
      "Individual_Awards": 0,
      "League":"Premier League",
      "Total_Followers": "106304",
      "Ad_value_equivalent":"270661.3"
    },
    {
      "id":39,
      "Name": "Boubakary Soumaré",
      "Nationality": "France",
      "Current_club": "Leicester City",
      "League_Position": "Defensive Midfield",
      "Myers_Briggs": "Inspirer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 78,
      "Predicted_Sponsorship_value": "1521",
      "Current_Market_value": "25,200,000",
      "Sponsor": "adidas",
      "Individual_Awards": 0,
      "League":"Premier League",
      "Total_Followers": "40431",
      "Ad_value_equivalent":"48739.6"
    },
    {
      "id":40,
      "Name": "Aleksandr Golovin",
      "Nationality": "Russia",
      "Current_club": "AS Monaco",
      "League_Position": "Attacking Midfield",
      "Myers_Briggs": "Scientist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 79,
      "Predicted_Sponsorship_value": "3113",
      "Current_Market_value": "25,200,000",
      "Sponsor": "Nike",
      "Individual_Awards": 0,
      "League":"Ligue 1",
      "Total_Followers": "475001",
      "Ad_value_equivalent":"118209"
    },
    {
      "id":41,
      "Name": "Benoît Badiashile",
      "Nationality": "France",
      "Current_club": "AS Monaco",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 76,
      "Predicted_Sponsorship_value": "3923",
      "Current_Market_value": "25,200,000",
      "Sponsor": "adidas",
      "Individual_Awards": 0,
      "League":"Ligue 1",
      "Total_Followers": "30241",
      "Ad_value_equivalent":"154872.9"
    },
    {
      "id":42,
      "Name": "Nabil Fekir",
      "Nationality": "France",
      "Current_club": "Real Betis Balompié",
      "League_Position": "Attacking Midfield",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 84,
      "Predicted_Sponsorship_value": "80908",
      "Current_Market_value": "22,500,000",
      "Sponsor": "Nike",
      "Individual_Awards": 3,
      "League":"LaLiga",
      "Total_Followers": "1440800",
      "Ad_value_equivalent":"702556.4"
    },
    {
      "id":43,
      "Name": "Daichi Kamada",
      "Nationality": "Japan",
      "Current_club": "Eintracht Frankfurt",
      "League_Position": "Attacking Midfield",
      "Myers_Briggs": "Performer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Asian",
      "Overall_rating": 79,
      "Predicted_Sponsorship_value": "6789",
      "Current_Market_value": "22,500,000",
      "Sponsor": "Nike",
      "Individual_Awards": 0,
      "League":"Budesliga",
      "Total_Followers": "80500",
      "Ad_value_equivalent":"214832.8"
    },
    {
      "id":44,
      "Name": "André Zambo Anguissa",
      "Nationality": "Cameroon",
      "Current_club": "SSC Napoli",
      "League_Position": "Defensive Midfield",
      "Myers_Briggs": "Inspirer",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 78,
      "Predicted_Sponsorship_value": "579",
      "Current_Market_value": "22,500,000",
      "Sponsor": "Nike",
      "Individual_Awards": 0,
      "League":"Serie A",
      "Total_Followers": "184109",
      "Ad_value_equivalent":"17135.3"
    },
    {
      "id":45,
      "Name": "Jason Denayer",
      "Nationality": "Belgium",
      "Current_club": "Olympique Lyon",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 80,
      "Predicted_Sponsorship_value": "26713",
      "Current_Market_value": "22,500,000",
      "Sponsor": "Nike",
      "Individual_Awards": 4,
      "League":"Ligue 1",
      "Total_Followers": "606700",
      "Ad_value_equivalent":"371935.2"
    },
    {
      "id":46,
      "Name": "Robin Le Normand",
      "Nationality": "France",
      "Current_club": "Real Sociedad",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "White",
      "Overall_rating": 79,
      "Predicted_Sponsorship_value": "8207",
      "Current_Market_value": "22,500,000",
      "Sponsor": "adidas",
      "Individual_Awards": 0,
      "League":"LaLiga",
      "Total_Followers": "31636",
      "Ad_value_equivalent":"311675"
    },
    {
      "id":47,
      "Name": "Saïd Benrahma",
      "Nationality": "Algeria",
      "Current_club": "West Ham United",
      "League_Position": "Left Winger",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 77,
      "Predicted_Sponsorship_value": "23996",
      "Current_Market_value": "22,500,000",
      "Sponsor": "adidas",
      "Individual_Awards": 4,
      "League":"Premier League",
      "Total_Followers": "1766800",
      "Ad_value_equivalent":"173564.3"
    },
    {
      "id":48,
      "Name": "Giovanni Di Lorenzo",
      "Nationality": "Italy",
      "Current_club": "SSC Napoli",
      "League_Position": "Right-Back",
      "Myers_Briggs": "Duty Fulfiller",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 80,
      "Predicted_Sponsorship_value": "11217",
      "Current_Market_value": "21,600,000",
      "Sponsor": "Puma",
      "Individual_Awards": 0,
      "League":"Serie A",
      "Total_Followers": "458000",
      "Ad_value_equivalent":"323559.6"
    },
    {
      "id":49,
      "Name": "Rayan Cherki",
      "Nationality": "France",
      "Current_club": "Olympique Lyon",
      "League_Position": "Midfield",
      "Myers_Briggs": "Artist",
      "Personality_Type": "Introvert",
      "Ethnicity": "White",
      "Overall_rating": 73,
      "Predicted_Sponsorship_value": "8721",
      "Current_Market_value": "20,700,000",
      "Sponsor": "adidas",
      "Individual_Awards": 0,
      "League":"Ligue 1",
      "Total_Followers": "380000",
      "Ad_value_equivalent":"278714.5"
    },
    {
      "id":50,
      "Name": "Odilon Kossounou",
      "Nationality": "Cote d'Ivoire",
      "Current_club": "Bayer 04 Leverkusen",
      "League_Position": "Centre-Back",
      "Myers_Briggs": "Guardian",
      "Personality_Type": "Extrovert",
      "Ethnicity": "Black",
      "Overall_rating": 74,
      "Predicted_Sponsorship_value": "1826",
      "Current_Market_value": "20,700,000",
      "Sponsor": "Puma",
      "Individual_Awards": 0,
      "League":"Budesliga",
      "Total_Followers": "36205",
      "Ad_value_equivalent":"61698"
    }
  ]